BUILD-6088 Create SECURITY.md
SonarSource/vault-action-wrapper pull request #42
Opened 2024-08-22 14:20 UTC by SamirM-BE

This file needs to be present for all Sonar public repositories, for more information please refer to BUILD-6088.

2024-08-28 08:12 UTC, sebastienvermeille requested changes
It breaks pre-commit checks

2024-08-28 14:25 UTC, tomverin approved these changes

2024-08-29 08:28 UTC, sebastienvermeille requested changes
excluding SECURITY.md is not a proper solution IMHO. The markdown should be fixed so that the  checks pass not the tool.

2024-09-13 10:55 UTC, sebastienvermeille approved these changes

2024-09-13 10:55 UTC, merged